"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/Nav'
import { Providers } from './components/Providers'
import { motion, AnimatePresence } from "framer-motion";
import { useEffect, useState } from "react";
import Loader from './components/Loader'
import Banner from './components/Banner'
import Footer from './components/Footer'
import { usePathname } from 'next/navigation' 


const inter = Inter({ subsets: ['latin'] })



// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname()
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    loading
      ? document.querySelector("body")?.classList.add("loading")
      : document.querySelector("body")?.classList.remove("loading");
  }, [loading]);


  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth" >
      {/* #305043 */}
      <body
        className={`${inter.className} bg-gradient-to-b from-gray-800 via-[#314F44] to-[#0c1915]   text-black dark:bg-[#314F44] dark:text-white  selection:bg-gray-50 h-auto scroll-smooth`}
      >
        
        <AnimatePresence>
          {loading ? (
            <motion.div
              key="loader"
              className="h-full w-full absolute    "
            >
              <Loader setLoading={setLoading} />
            </motion.div>
          ) : (
            <Providers>
              <Nav />
              {!loading && pathname === "/" ? (
                <>
                  <Banner />
                  <div className=" final block -z-20 ">
                    <motion.video
                    
                      transition={{ ease: "anticipate", duration: 1.6 }}
                      src={`/HEARTHSTONE.mp4`}
                      autoPlay
                      loop
                      muted
                      layoutId="main-image-1"
                      className="w-[85vw] h-[85vh] mx-auto object-cover "
                    ></motion.video>
                  </div>
                </>
              ) : (
                <></>
              )}

              <main>{children}</main>
              <Footer />
            </Providers>
          )}
        </AnimatePresence>
      </body>
    </html>
  );
}
