"use client"

import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from './components/Nav'
import Contact from './components/Contact'
import { Providers } from './components/Providers'
import { motion, AnimateSharedLayout, AnimatePresence } from "framer-motion";
import { useEffect, useState } from "react";
import Loader from './components/Loader'
import Banner from './components/Banner'


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    loading
      ? document.querySelector("body")?.classList.add("loading")
      : document.querySelector("body")?.classList.remove("loading");
  }, [loading]);


  return (
    <html lang="en" suppressHydrationWarning>
      
      

        
              <AnimatePresence>
                <body className={`${inter.className} bg-[#7e9fab42]  text-black dark:bg-gray-900 dark:text-white  selection:bg-gray-50`}>
              {loading ? (
              <motion.div key='loader'>
                <Loader setLoading={setLoading} />
              </motion.div>
            ) : (
              <Providers>
                <Nav/>
                <Banner/>
                {!loading && (
              <div className=' final translate-y-[25%] w-full'>
                <motion.img
                  transition={{ ease: "anticipate", duration: 2.0 }}
                  src={`/image-2.jpg`}
                  layoutId='main-image-1'
                  className='w-[85vw] h-[80vh] mx-auto object-cover duration-0 '
                />
              </div>
            )}
                <main >
                    {children}
                </main>
                <Contact/>
              </Providers>
            )}
            </body>
              </AnimatePresence>            
         

        
      
    </html>
  )
}
